### ISSUE TITLE
Two other issues

### ISSUE THREAD

**Issue by UnityAnthony** [MinaPecheux/UnityTutorials-RTS#4]
Tree Prefab is missing from Terrain objects

and the Fog of war shader doesn't render

<img width="960" alt="rts" src="https://user-images.githubusercontent.com/63601248/150387261-296442d5-6cb6-466b-8fd2-90aab4ddbd81.png">

**Comment by UnityAnthony** [comment]
Shader is easy fix remove d3d11 from the #pragma exclude_renderers  line

**Comment by UnityAnthony** [comment]
Actually that breaks tree rendering

**Comment by MinaPecheux** [comment]
Hi again!
So the tree prefabs are missing because I'm using assets from the store that I didn't commit... (the low-poly pack). Not sure how to go about this: as I explained in the tutorial it's one possibility but I want people to remain free to pick what they want, so I'm not committing all assets...

Happy to get your opinion on this! :)

About the FOV shader: yes I know, sadly there are some breaking changes between the various Unity versions... this has been noticed in #2 that is still open.
I'm not well-informed enough about Unity's inner workings with shaders to solve it, any help would be much appreciated! :D
