### ISSUE TITLE
Any luck trying to run it with Unity 6?

### ISSUE THREAD

**Issue by vpereira** [MinaPecheux/UnityTutorials-RTS#8]
I get a lot of exceptions when trying to run the the Core scene in Unity 6..

**Comment by MinaPecheux** [comment]
Heya! Thanks for your interest in the project :)
Unfortunately, this project was made a few years ago with Unity 2020/2021+ versions, and I don't have the time to update it or make it work with the new Unity 6 system - sorry!

But many thanks for your comment, because it had me add this warning in the Readme of the repo for future reference :)

I hope you understand,
and I'll close this issue since this is not a "bug" per se but a version incompatibility ;)

Cheers!

**Comment by vpereira** [comment]
> I hope you understand,

Hey Thank you for letting me know! No issues at all, I know how it is.

Cheers!
